version: '3.4'

services:
  openhabdeebot:
    image: openhabdeebot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: openhabdeebot
    environment: 
      - email=${email}
      - password=${password}
      - device_id=${device_id}
      - country=${country}
      - continent=${continent}
      - verify_ssl=${verify_ssl}
      - mqtt_client_id=${mqtt_client_id}
      - mqtt_client_host=${mqtt_client_host}
      - mqtt_client_port=${mqtt_client_port}
      - mqtt_client_username=${mqtt_client_username}
      - mqtt_client_password=${mqtt_client_password}
      - mqtt_client_keepalive=${mqtt_client_keepalive}
      - mqtt_client_bind_address=${mqtt_client_bind_address}
      - mqtt_client_root_topic=${mqtt_client_root_topic}
